//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCartao
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/SmartPayments/", ConfigurationName="ServiceCartao.CreditCardValidatorSoap")]
    internal interface CreditCardValidatorSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/GetCardType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetCardTypeAsync(string CardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/IsCommercialCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> IsCommercialCardAsync(string CardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/ValidCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> ValidCardAsync(string CardNumber, string ExpDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/ValidCardLength", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> ValidCardLengthAsync(string CardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/ValidExpDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> ValidExpDateAsync(string ExpDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/ValidMod10", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> ValidMod10Async(string CardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/GetNetworkID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceCartao.Response> GetNetworkIDAsync(string UserName, string Password, string CardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/IsFSACard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> IsFSACardAsync(string CardNumber, string PNRef, string Vendor, string CcInfoKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/IsValidCheckRoutingNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> IsValidCheckRoutingNumberAsync(string RoutingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/IsDebitCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> IsDebitCardAsync(string CardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SmartPayments/gVerifyCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> gVerifyCheckAsync(string UserName, string Password, int Vendor, string TransitNum, string AccountNum);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/SmartPayments/")]
    public partial class Response
    {
        
        private int resultField;
        
        private string respMSGField;
        
        private string messageField;
        
        private string message1Field;
        
        private string message2Field;
        
        private string authCodeField;
        
        private string pNRefField;
        
        private string hostCodeField;
        
        private string hostURLField;
        
        private string receiptURLField;
        
        private string getAVSResultField;
        
        private string getAVSResultTXTField;
        
        private string getStreetMatchTXTField;
        
        private string getZipMatchTXTField;
        
        private string getCVResultField;
        
        private string getCVResultTXTField;
        
        private string getGetOrigResultField;
        
        private string getCommercialCardField;
        
        private string workingKeyField;
        
        private string keyPointerField;
        
        private string extDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RespMSG
        {
            get
            {
                return this.respMSGField;
            }
            set
            {
                this.respMSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message1
        {
            get
            {
                return this.message1Field;
            }
            set
            {
                this.message1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Message2
        {
            get
            {
                return this.message2Field;
            }
            set
            {
                this.message2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AuthCode
        {
            get
            {
                return this.authCodeField;
            }
            set
            {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PNRef
        {
            get
            {
                return this.pNRefField;
            }
            set
            {
                this.pNRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string HostCode
        {
            get
            {
                return this.hostCodeField;
            }
            set
            {
                this.hostCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string HostURL
        {
            get
            {
                return this.hostURLField;
            }
            set
            {
                this.hostURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ReceiptURL
        {
            get
            {
                return this.receiptURLField;
            }
            set
            {
                this.receiptURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string GetAVSResult
        {
            get
            {
                return this.getAVSResultField;
            }
            set
            {
                this.getAVSResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string GetAVSResultTXT
        {
            get
            {
                return this.getAVSResultTXTField;
            }
            set
            {
                this.getAVSResultTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string GetStreetMatchTXT
        {
            get
            {
                return this.getStreetMatchTXTField;
            }
            set
            {
                this.getStreetMatchTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string GetZipMatchTXT
        {
            get
            {
                return this.getZipMatchTXTField;
            }
            set
            {
                this.getZipMatchTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string GetCVResult
        {
            get
            {
                return this.getCVResultField;
            }
            set
            {
                this.getCVResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string GetCVResultTXT
        {
            get
            {
                return this.getCVResultTXTField;
            }
            set
            {
                this.getCVResultTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string GetGetOrigResult
        {
            get
            {
                return this.getGetOrigResultField;
            }
            set
            {
                this.getGetOrigResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string GetCommercialCard
        {
            get
            {
                return this.getCommercialCardField;
            }
            set
            {
                this.getCommercialCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string WorkingKey
        {
            get
            {
                return this.workingKeyField;
            }
            set
            {
                this.workingKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string KeyPointer
        {
            get
            {
                return this.keyPointerField;
            }
            set
            {
                this.keyPointerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ExtData
        {
            get
            {
                return this.extDataField;
            }
            set
            {
                this.extDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal interface CreditCardValidatorSoapChannel : ServiceCartao.CreditCardValidatorSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal partial class CreditCardValidatorSoapClient : System.ServiceModel.ClientBase<ServiceCartao.CreditCardValidatorSoap>, ServiceCartao.CreditCardValidatorSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CreditCardValidatorSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CreditCardValidatorSoapClient.GetBindingForEndpoint(endpointConfiguration), CreditCardValidatorSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditCardValidatorSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CreditCardValidatorSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditCardValidatorSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CreditCardValidatorSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CreditCardValidatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetCardTypeAsync(string CardNumber)
        {
            return base.Channel.GetCardTypeAsync(CardNumber);
        }
        
        public System.Threading.Tasks.Task<bool> IsCommercialCardAsync(string CardNumber)
        {
            return base.Channel.IsCommercialCardAsync(CardNumber);
        }
        
        public System.Threading.Tasks.Task<int> ValidCardAsync(string CardNumber, string ExpDate)
        {
            return base.Channel.ValidCardAsync(CardNumber, ExpDate);
        }
        
        public System.Threading.Tasks.Task<bool> ValidCardLengthAsync(string CardNumber)
        {
            return base.Channel.ValidCardLengthAsync(CardNumber);
        }
        
        public System.Threading.Tasks.Task<bool> ValidExpDateAsync(string ExpDate)
        {
            return base.Channel.ValidExpDateAsync(ExpDate);
        }
        
        public System.Threading.Tasks.Task<bool> ValidMod10Async(string CardNumber)
        {
            return base.Channel.ValidMod10Async(CardNumber);
        }
        
        public System.Threading.Tasks.Task<ServiceCartao.Response> GetNetworkIDAsync(string UserName, string Password, string CardNumber)
        {
            return base.Channel.GetNetworkIDAsync(UserName, Password, CardNumber);
        }
        
        public System.Threading.Tasks.Task<bool> IsFSACardAsync(string CardNumber, string PNRef, string Vendor, string CcInfoKey)
        {
            return base.Channel.IsFSACardAsync(CardNumber, PNRef, Vendor, CcInfoKey);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidCheckRoutingNumberAsync(string RoutingNumber)
        {
            return base.Channel.IsValidCheckRoutingNumberAsync(RoutingNumber);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> IsDebitCardAsync(string CardNumber)
        {
            return base.Channel.IsDebitCardAsync(CardNumber);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> gVerifyCheckAsync(string UserName, string Password, int Vendor, string TransitNum, string AccountNum)
        {
            return base.Channel.gVerifyCheckAsync(UserName, Password, Vendor, TransitNum, AccountNum);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CreditCardValidatorSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardValidatorSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CreditCardValidatorSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://secure.ftipgw.com/ArgoFire/validate.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CreditCardValidatorSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://secure.ftipgw.com/ArgoFire/validate.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CreditCardValidatorSoap,
            
            CreditCardValidatorSoap12,
        }
    }
}
