//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceNotificacao
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notificacao", Namespace="http://tempuri.org/")]
    internal partial class Notificacao : object
    {
        
        private int IdField;
        
        private string TituloField;
        
        private string MensagemField;
        
        private ServiceNotificacao.TipoNotificacao TipoField;
        
        private bool LidaField;
        
        private System.DateTime CreatedAtField;
        
        private string UtilizadorIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Titulo
        {
            get
            {
                return this.TituloField;
            }
            set
            {
                this.TituloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        internal ServiceNotificacao.TipoNotificacao Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        internal bool Lida
        {
            get
            {
                return this.LidaField;
            }
            set
            {
                this.LidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        internal System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        internal string UtilizadorId
        {
            get
            {
                return this.UtilizadorIdField;
            }
            set
            {
                this.UtilizadorIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoNotificacao", Namespace="http://tempuri.org/")]
    internal enum TipoNotificacao : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Informacao = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alerta = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aviso = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erro = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucesso = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNotificacao.NotificacaoRepositoryServiceSoap")]
    internal interface NotificacaoRepositoryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirNotificacao", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceNotificacao.InserirNotificacaoResponse> InserirNotificacaoAsync(ServiceNotificacao.InserirNotificacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterNotificacoesPorUtilizador", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceNotificacao.ObterNotificacoesPorUtilizadorResponse> ObterNotificacoesPorUtilizadorAsync(ServiceNotificacao.ObterNotificacoesPorUtilizadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MarcarNotificacaoComoLida", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> MarcarNotificacaoComoLidaAsync(int notificacaoId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class InserirNotificacaoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirNotificacao", Namespace="http://tempuri.org/", Order=0)]
        public ServiceNotificacao.InserirNotificacaoRequestBody Body;
        
        public InserirNotificacaoRequest()
        {
        }
        
        public InserirNotificacaoRequest(ServiceNotificacao.InserirNotificacaoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class InserirNotificacaoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceNotificacao.Notificacao notificacao;
        
        public InserirNotificacaoRequestBody()
        {
        }
        
        public InserirNotificacaoRequestBody(ServiceNotificacao.Notificacao notificacao)
        {
            this.notificacao = notificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class InserirNotificacaoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirNotificacaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceNotificacao.InserirNotificacaoResponseBody Body;
        
        public InserirNotificacaoResponse()
        {
        }
        
        public InserirNotificacaoResponse(ServiceNotificacao.InserirNotificacaoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class InserirNotificacaoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceNotificacao.Notificacao InserirNotificacaoResult;
        
        public InserirNotificacaoResponseBody()
        {
        }
        
        public InserirNotificacaoResponseBody(ServiceNotificacao.Notificacao InserirNotificacaoResult)
        {
            this.InserirNotificacaoResult = InserirNotificacaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ObterNotificacoesPorUtilizadorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterNotificacoesPorUtilizador", Namespace="http://tempuri.org/", Order=0)]
        public ServiceNotificacao.ObterNotificacoesPorUtilizadorRequestBody Body;
        
        public ObterNotificacoesPorUtilizadorRequest()
        {
        }
        
        public ObterNotificacoesPorUtilizadorRequest(ServiceNotificacao.ObterNotificacoesPorUtilizadorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ObterNotificacoesPorUtilizadorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string utilizadorId;
        
        public ObterNotificacoesPorUtilizadorRequestBody()
        {
        }
        
        public ObterNotificacoesPorUtilizadorRequestBody(string utilizadorId)
        {
            this.utilizadorId = utilizadorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ObterNotificacoesPorUtilizadorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterNotificacoesPorUtilizadorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceNotificacao.ObterNotificacoesPorUtilizadorResponseBody Body;
        
        public ObterNotificacoesPorUtilizadorResponse()
        {
        }
        
        public ObterNotificacoesPorUtilizadorResponse(ServiceNotificacao.ObterNotificacoesPorUtilizadorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ObterNotificacoesPorUtilizadorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceNotificacao.Notificacao[] ObterNotificacoesPorUtilizadorResult;
        
        public ObterNotificacoesPorUtilizadorResponseBody()
        {
        }
        
        public ObterNotificacoesPorUtilizadorResponseBody(ServiceNotificacao.Notificacao[] ObterNotificacoesPorUtilizadorResult)
        {
            this.ObterNotificacoesPorUtilizadorResult = ObterNotificacoesPorUtilizadorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal interface NotificacaoRepositoryServiceSoapChannel : ServiceNotificacao.NotificacaoRepositoryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal partial class NotificacaoRepositoryServiceSoapClient : System.ServiceModel.ClientBase<ServiceNotificacao.NotificacaoRepositoryServiceSoap>, ServiceNotificacao.NotificacaoRepositoryServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NotificacaoRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NotificacaoRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), NotificacaoRepositoryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificacaoRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NotificacaoRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificacaoRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NotificacaoRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificacaoRepositoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceNotificacao.InserirNotificacaoResponse> ServiceNotificacao.NotificacaoRepositoryServiceSoap.InserirNotificacaoAsync(ServiceNotificacao.InserirNotificacaoRequest request)
        {
            return base.Channel.InserirNotificacaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceNotificacao.InserirNotificacaoResponse> InserirNotificacaoAsync(ServiceNotificacao.Notificacao notificacao)
        {
            ServiceNotificacao.InserirNotificacaoRequest inValue = new ServiceNotificacao.InserirNotificacaoRequest();
            inValue.Body = new ServiceNotificacao.InserirNotificacaoRequestBody();
            inValue.Body.notificacao = notificacao;
            return ((ServiceNotificacao.NotificacaoRepositoryServiceSoap)(this)).InserirNotificacaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceNotificacao.ObterNotificacoesPorUtilizadorResponse> ServiceNotificacao.NotificacaoRepositoryServiceSoap.ObterNotificacoesPorUtilizadorAsync(ServiceNotificacao.ObterNotificacoesPorUtilizadorRequest request)
        {
            return base.Channel.ObterNotificacoesPorUtilizadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceNotificacao.ObterNotificacoesPorUtilizadorResponse> ObterNotificacoesPorUtilizadorAsync(string utilizadorId)
        {
            ServiceNotificacao.ObterNotificacoesPorUtilizadorRequest inValue = new ServiceNotificacao.ObterNotificacoesPorUtilizadorRequest();
            inValue.Body = new ServiceNotificacao.ObterNotificacoesPorUtilizadorRequestBody();
            inValue.Body.utilizadorId = utilizadorId;
            return ((ServiceNotificacao.NotificacaoRepositoryServiceSoap)(this)).ObterNotificacoesPorUtilizadorAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> MarcarNotificacaoComoLidaAsync(int notificacaoId)
        {
            return base.Channel.MarcarNotificacaoComoLidaAsync(notificacaoId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NotificacaoRepositoryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NotificacaoRepositoryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NotificacaoRepositoryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/NotificacaoRepositoryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NotificacaoRepositoryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/NotificacaoRepositoryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NotificacaoRepositoryServiceSoap,
            
            NotificacaoRepositoryServiceSoap12,
        }
    }
}
