//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLeituras
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Leituras", Namespace="http://tempuri.org/")]
    internal partial class Leituras : object
    {
        
        private int IdField;
        
        private int SensorIdField;
        
        private float ValorField;
        
        private System.DateTime DataHoraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int SensorId
        {
            get
            {
                return this.SensorIdField;
            }
            set
            {
                this.SensorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal float Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        internal System.DateTime DataHora
        {
            get
            {
                return this.DataHoraField;
            }
            set
            {
                this.DataHoraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeiturasStock", Namespace="http://tempuri.org/")]
    internal partial class LeiturasStock : object
    {
        
        private ServiceLeituras.Temp[] TemperaturaField;
        
        private ServiceLeituras.Hum[] HumidadeField;
        
        private ServiceLeituras.Lum[] LuminosidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal ServiceLeituras.Temp[] Temperatura
        {
            get
            {
                return this.TemperaturaField;
            }
            set
            {
                this.TemperaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        internal ServiceLeituras.Hum[] Humidade
        {
            get
            {
                return this.HumidadeField;
            }
            set
            {
                this.HumidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal ServiceLeituras.Lum[] Luminosidade
        {
            get
            {
                return this.LuminosidadeField;
            }
            set
            {
                this.LuminosidadeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Temp", Namespace="http://tempuri.org/")]
    internal partial class Temp : object
    {
        
        private double temperaturaField;
        
        private System.DateTime dataHoraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal double temperatura
        {
            get
            {
                return this.temperaturaField;
            }
            set
            {
                this.temperaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        internal System.DateTime dataHora
        {
            get
            {
                return this.dataHoraField;
            }
            set
            {
                this.dataHoraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hum", Namespace="http://tempuri.org/")]
    internal partial class Hum : object
    {
        
        private double humidadeField;
        
        private System.DateTime dataHoraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal double humidade
        {
            get
            {
                return this.humidadeField;
            }
            set
            {
                this.humidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        internal System.DateTime dataHora
        {
            get
            {
                return this.dataHoraField;
            }
            set
            {
                this.dataHoraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lum", Namespace="http://tempuri.org/")]
    internal partial class Lum : object
    {
        
        private int luminosidadeField;
        
        private System.DateTime dataHoraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int luminosidade
        {
            get
            {
                return this.luminosidadeField;
            }
            set
            {
                this.luminosidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        internal System.DateTime dataHora
        {
            get
            {
                return this.dataHoraField;
            }
            set
            {
                this.dataHoraField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLeituras.LeiturasRepositoryServiceSoap")]
    internal interface LeiturasRepositoryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirLeitura", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLeituras.InserirLeituraResponse> InserirLeituraAsync(ServiceLeituras.InserirLeituraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterLeiturasPorSensor", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasPorSensorResponse> ObterLeiturasPorSensorAsync(ServiceLeituras.ObterLeiturasPorSensorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterLeiturasStock", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasStockResponse> ObterLeiturasStockAsync(ServiceLeituras.ObterLeiturasStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterLeiturasAdega", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasAdegaResponse> ObterLeiturasAdegaAsync(ServiceLeituras.ObterLeiturasAdegaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class InserirLeituraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirLeitura", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.InserirLeituraRequestBody Body;
        
        public InserirLeituraRequest()
        {
        }
        
        public InserirLeituraRequest(ServiceLeituras.InserirLeituraRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class InserirLeituraRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLeituras.Leituras leitura;
        
        public InserirLeituraRequestBody()
        {
        }
        
        public InserirLeituraRequestBody(ServiceLeituras.Leituras leitura)
        {
            this.leitura = leitura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class InserirLeituraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirLeituraResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.InserirLeituraResponseBody Body;
        
        public InserirLeituraResponse()
        {
        }
        
        public InserirLeituraResponse(ServiceLeituras.InserirLeituraResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class InserirLeituraResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLeituras.Leituras InserirLeituraResult;
        
        public InserirLeituraResponseBody()
        {
        }
        
        public InserirLeituraResponseBody(ServiceLeituras.Leituras InserirLeituraResult)
        {
            this.InserirLeituraResult = InserirLeituraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ObterLeiturasPorSensorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterLeiturasPorSensor", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.ObterLeiturasPorSensorRequestBody Body;
        
        public ObterLeiturasPorSensorRequest()
        {
        }
        
        public ObterLeiturasPorSensorRequest(ServiceLeituras.ObterLeiturasPorSensorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ObterLeiturasPorSensorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sensorId;
        
        public ObterLeiturasPorSensorRequestBody()
        {
        }
        
        public ObterLeiturasPorSensorRequestBody(int sensorId)
        {
            this.sensorId = sensorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ObterLeiturasPorSensorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterLeiturasPorSensorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.ObterLeiturasPorSensorResponseBody Body;
        
        public ObterLeiturasPorSensorResponse()
        {
        }
        
        public ObterLeiturasPorSensorResponse(ServiceLeituras.ObterLeiturasPorSensorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ObterLeiturasPorSensorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLeituras.Leituras[] ObterLeiturasPorSensorResult;
        
        public ObterLeiturasPorSensorResponseBody()
        {
        }
        
        public ObterLeiturasPorSensorResponseBody(ServiceLeituras.Leituras[] ObterLeiturasPorSensorResult)
        {
            this.ObterLeiturasPorSensorResult = ObterLeiturasPorSensorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ObterLeiturasStockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterLeiturasStock", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.ObterLeiturasStockRequestBody Body;
        
        public ObterLeiturasStockRequest()
        {
        }
        
        public ObterLeiturasStockRequest(ServiceLeituras.ObterLeiturasStockRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ObterLeiturasStockRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int stockId;
        
        public ObterLeiturasStockRequestBody()
        {
        }
        
        public ObterLeiturasStockRequestBody(int stockId)
        {
            this.stockId = stockId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ObterLeiturasStockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterLeiturasStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.ObterLeiturasStockResponseBody Body;
        
        public ObterLeiturasStockResponse()
        {
        }
        
        public ObterLeiturasStockResponse(ServiceLeituras.ObterLeiturasStockResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ObterLeiturasStockResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLeituras.LeiturasStock ObterLeiturasStockResult;
        
        public ObterLeiturasStockResponseBody()
        {
        }
        
        public ObterLeiturasStockResponseBody(ServiceLeituras.LeiturasStock ObterLeiturasStockResult)
        {
            this.ObterLeiturasStockResult = ObterLeiturasStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ObterLeiturasAdegaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterLeiturasAdega", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.ObterLeiturasAdegaRequestBody Body;
        
        public ObterLeiturasAdegaRequest()
        {
        }
        
        public ObterLeiturasAdegaRequest(ServiceLeituras.ObterLeiturasAdegaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ObterLeiturasAdegaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int adegaId;
        
        public ObterLeiturasAdegaRequestBody()
        {
        }
        
        public ObterLeiturasAdegaRequestBody(int adegaId)
        {
            this.adegaId = adegaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ObterLeiturasAdegaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterLeiturasAdegaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.ObterLeiturasAdegaResponseBody Body;
        
        public ObterLeiturasAdegaResponse()
        {
        }
        
        public ObterLeiturasAdegaResponse(ServiceLeituras.ObterLeiturasAdegaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ObterLeiturasAdegaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLeituras.LeiturasStock ObterLeiturasAdegaResult;
        
        public ObterLeiturasAdegaResponseBody()
        {
        }
        
        public ObterLeiturasAdegaResponseBody(ServiceLeituras.LeiturasStock ObterLeiturasAdegaResult)
        {
            this.ObterLeiturasAdegaResult = ObterLeiturasAdegaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal interface LeiturasRepositoryServiceSoapChannel : ServiceLeituras.LeiturasRepositoryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal partial class LeiturasRepositoryServiceSoapClient : System.ServiceModel.ClientBase<ServiceLeituras.LeiturasRepositoryServiceSoap>, ServiceLeituras.LeiturasRepositoryServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LeiturasRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LeiturasRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), LeiturasRepositoryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeiturasRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LeiturasRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeiturasRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LeiturasRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeiturasRepositoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLeituras.InserirLeituraResponse> ServiceLeituras.LeiturasRepositoryServiceSoap.InserirLeituraAsync(ServiceLeituras.InserirLeituraRequest request)
        {
            return base.Channel.InserirLeituraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLeituras.InserirLeituraResponse> InserirLeituraAsync(ServiceLeituras.Leituras leitura)
        {
            ServiceLeituras.InserirLeituraRequest inValue = new ServiceLeituras.InserirLeituraRequest();
            inValue.Body = new ServiceLeituras.InserirLeituraRequestBody();
            inValue.Body.leitura = leitura;
            return ((ServiceLeituras.LeiturasRepositoryServiceSoap)(this)).InserirLeituraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasPorSensorResponse> ServiceLeituras.LeiturasRepositoryServiceSoap.ObterLeiturasPorSensorAsync(ServiceLeituras.ObterLeiturasPorSensorRequest request)
        {
            return base.Channel.ObterLeiturasPorSensorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasPorSensorResponse> ObterLeiturasPorSensorAsync(int sensorId)
        {
            ServiceLeituras.ObterLeiturasPorSensorRequest inValue = new ServiceLeituras.ObterLeiturasPorSensorRequest();
            inValue.Body = new ServiceLeituras.ObterLeiturasPorSensorRequestBody();
            inValue.Body.sensorId = sensorId;
            return ((ServiceLeituras.LeiturasRepositoryServiceSoap)(this)).ObterLeiturasPorSensorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasStockResponse> ServiceLeituras.LeiturasRepositoryServiceSoap.ObterLeiturasStockAsync(ServiceLeituras.ObterLeiturasStockRequest request)
        {
            return base.Channel.ObterLeiturasStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasStockResponse> ObterLeiturasStockAsync(int stockId)
        {
            ServiceLeituras.ObterLeiturasStockRequest inValue = new ServiceLeituras.ObterLeiturasStockRequest();
            inValue.Body = new ServiceLeituras.ObterLeiturasStockRequestBody();
            inValue.Body.stockId = stockId;
            return ((ServiceLeituras.LeiturasRepositoryServiceSoap)(this)).ObterLeiturasStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasAdegaResponse> ServiceLeituras.LeiturasRepositoryServiceSoap.ObterLeiturasAdegaAsync(ServiceLeituras.ObterLeiturasAdegaRequest request)
        {
            return base.Channel.ObterLeiturasAdegaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasAdegaResponse> ObterLeiturasAdegaAsync(int adegaId)
        {
            ServiceLeituras.ObterLeiturasAdegaRequest inValue = new ServiceLeituras.ObterLeiturasAdegaRequest();
            inValue.Body = new ServiceLeituras.ObterLeiturasAdegaRequestBody();
            inValue.Body.adegaId = adegaId;
            return ((ServiceLeituras.LeiturasRepositoryServiceSoap)(this)).ObterLeiturasAdegaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LeiturasRepositoryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LeiturasRepositoryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LeiturasRepositoryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/LeiturasRepositoryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LeiturasRepositoryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/LeiturasRepositoryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LeiturasRepositoryServiceSoap,
            
            LeiturasRepositoryServiceSoap12,
        }
    }
}
