//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLeituras
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Leituras", Namespace="http://tempuri.org/")]
    public partial class Leituras : object
    {
        
        private int IdField;
        
        private int SensorIdField;
        
        private float ValorField;
        
        private System.DateTime DataHoraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SensorId
        {
            get
            {
                return this.SensorIdField;
            }
            set
            {
                this.SensorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DataHora
        {
            get
            {
                return this.DataHoraField;
            }
            set
            {
                this.DataHoraField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLeituras.LeiturasRepositoryServiceSoap")]
    public interface LeiturasRepositoryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirLeitura", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLeituras.InserirLeituraResponse> InserirLeituraAsync(ServiceLeituras.InserirLeituraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterLeiturasPorSensor", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasPorSensorResponse> ObterLeiturasPorSensorAsync(ServiceLeituras.ObterLeiturasPorSensorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirLeituraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirLeitura", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.InserirLeituraRequestBody Body;
        
        public InserirLeituraRequest()
        {
        }
        
        public InserirLeituraRequest(ServiceLeituras.InserirLeituraRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirLeituraRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLeituras.Leituras leitura;
        
        public InserirLeituraRequestBody()
        {
        }
        
        public InserirLeituraRequestBody(ServiceLeituras.Leituras leitura)
        {
            this.leitura = leitura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirLeituraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirLeituraResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.InserirLeituraResponseBody Body;
        
        public InserirLeituraResponse()
        {
        }
        
        public InserirLeituraResponse(ServiceLeituras.InserirLeituraResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirLeituraResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLeituras.Leituras InserirLeituraResult;
        
        public InserirLeituraResponseBody()
        {
        }
        
        public InserirLeituraResponseBody(ServiceLeituras.Leituras InserirLeituraResult)
        {
            this.InserirLeituraResult = InserirLeituraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterLeiturasPorSensorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterLeiturasPorSensor", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.ObterLeiturasPorSensorRequestBody Body;
        
        public ObterLeiturasPorSensorRequest()
        {
        }
        
        public ObterLeiturasPorSensorRequest(ServiceLeituras.ObterLeiturasPorSensorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterLeiturasPorSensorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sensorId;
        
        public ObterLeiturasPorSensorRequestBody()
        {
        }
        
        public ObterLeiturasPorSensorRequestBody(int sensorId)
        {
            this.sensorId = sensorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterLeiturasPorSensorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterLeiturasPorSensorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceLeituras.ObterLeiturasPorSensorResponseBody Body;
        
        public ObterLeiturasPorSensorResponse()
        {
        }
        
        public ObterLeiturasPorSensorResponse(ServiceLeituras.ObterLeiturasPorSensorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterLeiturasPorSensorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLeituras.Leituras[] ObterLeiturasPorSensorResult;
        
        public ObterLeiturasPorSensorResponseBody()
        {
        }
        
        public ObterLeiturasPorSensorResponseBody(ServiceLeituras.Leituras[] ObterLeiturasPorSensorResult)
        {
            this.ObterLeiturasPorSensorResult = ObterLeiturasPorSensorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface LeiturasRepositoryServiceSoapChannel : ServiceLeituras.LeiturasRepositoryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class LeiturasRepositoryServiceSoapClient : System.ServiceModel.ClientBase<ServiceLeituras.LeiturasRepositoryServiceSoap>, ServiceLeituras.LeiturasRepositoryServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LeiturasRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LeiturasRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), LeiturasRepositoryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeiturasRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LeiturasRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeiturasRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LeiturasRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LeiturasRepositoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLeituras.InserirLeituraResponse> ServiceLeituras.LeiturasRepositoryServiceSoap.InserirLeituraAsync(ServiceLeituras.InserirLeituraRequest request)
        {
            return base.Channel.InserirLeituraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLeituras.InserirLeituraResponse> InserirLeituraAsync(ServiceLeituras.Leituras leitura)
        {
            ServiceLeituras.InserirLeituraRequest inValue = new ServiceLeituras.InserirLeituraRequest();
            inValue.Body = new ServiceLeituras.InserirLeituraRequestBody();
            inValue.Body.leitura = leitura;
            return ((ServiceLeituras.LeiturasRepositoryServiceSoap)(this)).InserirLeituraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasPorSensorResponse> ServiceLeituras.LeiturasRepositoryServiceSoap.ObterLeiturasPorSensorAsync(ServiceLeituras.ObterLeiturasPorSensorRequest request)
        {
            return base.Channel.ObterLeiturasPorSensorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLeituras.ObterLeiturasPorSensorResponse> ObterLeiturasPorSensorAsync(int sensorId)
        {
            ServiceLeituras.ObterLeiturasPorSensorRequest inValue = new ServiceLeituras.ObterLeiturasPorSensorRequest();
            inValue.Body = new ServiceLeituras.ObterLeiturasPorSensorRequestBody();
            inValue.Body.sensorId = sensorId;
            return ((ServiceLeituras.LeiturasRepositoryServiceSoap)(this)).ObterLeiturasPorSensorAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LeiturasRepositoryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LeiturasRepositoryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LeiturasRepositoryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/LeiturasRepositoryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LeiturasRepositoryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/LeiturasRepositoryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LeiturasRepositoryServiceSoap,
            
            LeiturasRepositoryServiceSoap12,
        }
    }
}
