//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAdega
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceAdega.TaskOfListOfAdega))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceAdega.TaskOfAdega))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceAdega.TaskOfBoolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceAdega.TaskOfInt32))]
    internal partial class Task : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskOfListOfAdega", Namespace="http://tempuri.org/")]
    internal partial class TaskOfListOfAdega : ServiceAdega.Task
    {
        
        private ServiceAdega.Adega[] ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal ServiceAdega.Adega[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskOfAdega", Namespace="http://tempuri.org/")]
    internal partial class TaskOfAdega : ServiceAdega.Task
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskOfBoolean", Namespace="http://tempuri.org/")]
    internal partial class TaskOfBoolean : ServiceAdega.Task
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskOfInt32", Namespace="http://tempuri.org/")]
    internal partial class TaskOfInt32 : ServiceAdega.Task
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adega", Namespace="http://tempuri.org/")]
    internal partial class Adega : object
    {
        
        private int IdField;
        
        private string LocalizacaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Localizacao
        {
            get
            {
                return this.LocalizacaoField;
            }
            set
            {
                this.LocalizacaoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAdega.AdegaRepositoryServiceSoap")]
    internal interface AdegaRepositoryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirAdega", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceAdega.InserirAdegaResponse> InserirAdegaAsync(ServiceAdega.InserirAdegaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodasAdegas", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceAdega.TodasAdegasResponse> TodasAdegasAsync(ServiceAdega.TodasAdegasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdegaById", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceAdega.AdegaByIdResponse> AdegaByIdAsync(ServiceAdega.AdegaByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarAdega", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceAdega.ModificarAdegaResponse> ModificarAdegaAsync(ServiceAdega.ModificarAdegaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApagarAdegaAsync", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceAdega.ApagarAdegaAsyncResponse> ApagarAdegaAsyncAsync(ServiceAdega.ApagarAdegaAsyncRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class InserirAdegaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirAdega", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAdega.InserirAdegaRequestBody Body;
        
        public InserirAdegaRequest()
        {
        }
        
        public InserirAdegaRequest(ServiceAdega.InserirAdegaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class InserirAdegaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string localizacao;
        
        public InserirAdegaRequestBody()
        {
        }
        
        public InserirAdegaRequestBody(string localizacao)
        {
            this.localizacao = localizacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class InserirAdegaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirAdegaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAdega.InserirAdegaResponseBody Body;
        
        public InserirAdegaResponse()
        {
        }
        
        public InserirAdegaResponse(ServiceAdega.InserirAdegaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class InserirAdegaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceAdega.TaskOfInt32 InserirAdegaResult;
        
        public InserirAdegaResponseBody()
        {
        }
        
        public InserirAdegaResponseBody(ServiceAdega.TaskOfInt32 InserirAdegaResult)
        {
            this.InserirAdegaResult = InserirAdegaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class TodasAdegasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodasAdegas", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAdega.TodasAdegasRequestBody Body;
        
        public TodasAdegasRequest()
        {
        }
        
        public TodasAdegasRequest(ServiceAdega.TodasAdegasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class TodasAdegasRequestBody
    {
        
        public TodasAdegasRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class TodasAdegasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodasAdegasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAdega.TodasAdegasResponseBody Body;
        
        public TodasAdegasResponse()
        {
        }
        
        public TodasAdegasResponse(ServiceAdega.TodasAdegasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class TodasAdegasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceAdega.TaskOfListOfAdega TodasAdegasResult;
        
        public TodasAdegasResponseBody()
        {
        }
        
        public TodasAdegasResponseBody(ServiceAdega.TaskOfListOfAdega TodasAdegasResult)
        {
            this.TodasAdegasResult = TodasAdegasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class AdegaByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdegaById", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAdega.AdegaByIdRequestBody Body;
        
        public AdegaByIdRequest()
        {
        }
        
        public AdegaByIdRequest(ServiceAdega.AdegaByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class AdegaByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public AdegaByIdRequestBody()
        {
        }
        
        public AdegaByIdRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class AdegaByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdegaByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAdega.AdegaByIdResponseBody Body;
        
        public AdegaByIdResponse()
        {
        }
        
        public AdegaByIdResponse(ServiceAdega.AdegaByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class AdegaByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceAdega.TaskOfAdega AdegaByIdResult;
        
        public AdegaByIdResponseBody()
        {
        }
        
        public AdegaByIdResponseBody(ServiceAdega.TaskOfAdega AdegaByIdResult)
        {
            this.AdegaByIdResult = AdegaByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ModificarAdegaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarAdega", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAdega.ModificarAdegaRequestBody Body;
        
        public ModificarAdegaRequest()
        {
        }
        
        public ModificarAdegaRequest(ServiceAdega.ModificarAdegaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ModificarAdegaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceAdega.Adega adega;
        
        public ModificarAdegaRequestBody()
        {
        }
        
        public ModificarAdegaRequestBody(ServiceAdega.Adega adega)
        {
            this.adega = adega;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ModificarAdegaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarAdegaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAdega.ModificarAdegaResponseBody Body;
        
        public ModificarAdegaResponse()
        {
        }
        
        public ModificarAdegaResponse(ServiceAdega.ModificarAdegaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ModificarAdegaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceAdega.TaskOfBoolean ModificarAdegaResult;
        
        public ModificarAdegaResponseBody()
        {
        }
        
        public ModificarAdegaResponseBody(ServiceAdega.TaskOfBoolean ModificarAdegaResult)
        {
            this.ModificarAdegaResult = ModificarAdegaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ApagarAdegaAsyncRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApagarAdegaAsync", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAdega.ApagarAdegaAsyncRequestBody Body;
        
        public ApagarAdegaAsyncRequest()
        {
        }
        
        public ApagarAdegaAsyncRequest(ServiceAdega.ApagarAdegaAsyncRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ApagarAdegaAsyncRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ApagarAdegaAsyncRequestBody()
        {
        }
        
        public ApagarAdegaAsyncRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ApagarAdegaAsyncResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApagarAdegaAsyncResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAdega.ApagarAdegaAsyncResponseBody Body;
        
        public ApagarAdegaAsyncResponse()
        {
        }
        
        public ApagarAdegaAsyncResponse(ServiceAdega.ApagarAdegaAsyncResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ApagarAdegaAsyncResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceAdega.TaskOfBoolean ApagarAdegaAsyncResult;
        
        public ApagarAdegaAsyncResponseBody()
        {
        }
        
        public ApagarAdegaAsyncResponseBody(ServiceAdega.TaskOfBoolean ApagarAdegaAsyncResult)
        {
            this.ApagarAdegaAsyncResult = ApagarAdegaAsyncResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal interface AdegaRepositoryServiceSoapChannel : ServiceAdega.AdegaRepositoryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal partial class AdegaRepositoryServiceSoapClient : System.ServiceModel.ClientBase<ServiceAdega.AdegaRepositoryServiceSoap>, ServiceAdega.AdegaRepositoryServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AdegaRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AdegaRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), AdegaRepositoryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdegaRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AdegaRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdegaRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AdegaRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdegaRepositoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceAdega.InserirAdegaResponse> ServiceAdega.AdegaRepositoryServiceSoap.InserirAdegaAsync(ServiceAdega.InserirAdegaRequest request)
        {
            return base.Channel.InserirAdegaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceAdega.InserirAdegaResponse> InserirAdegaAsync(string localizacao)
        {
            ServiceAdega.InserirAdegaRequest inValue = new ServiceAdega.InserirAdegaRequest();
            inValue.Body = new ServiceAdega.InserirAdegaRequestBody();
            inValue.Body.localizacao = localizacao;
            return ((ServiceAdega.AdegaRepositoryServiceSoap)(this)).InserirAdegaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceAdega.TodasAdegasResponse> ServiceAdega.AdegaRepositoryServiceSoap.TodasAdegasAsync(ServiceAdega.TodasAdegasRequest request)
        {
            return base.Channel.TodasAdegasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceAdega.TodasAdegasResponse> TodasAdegasAsync()
        {
            ServiceAdega.TodasAdegasRequest inValue = new ServiceAdega.TodasAdegasRequest();
            inValue.Body = new ServiceAdega.TodasAdegasRequestBody();
            return ((ServiceAdega.AdegaRepositoryServiceSoap)(this)).TodasAdegasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceAdega.AdegaByIdResponse> ServiceAdega.AdegaRepositoryServiceSoap.AdegaByIdAsync(ServiceAdega.AdegaByIdRequest request)
        {
            return base.Channel.AdegaByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceAdega.AdegaByIdResponse> AdegaByIdAsync(int id)
        {
            ServiceAdega.AdegaByIdRequest inValue = new ServiceAdega.AdegaByIdRequest();
            inValue.Body = new ServiceAdega.AdegaByIdRequestBody();
            inValue.Body.id = id;
            return ((ServiceAdega.AdegaRepositoryServiceSoap)(this)).AdegaByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceAdega.ModificarAdegaResponse> ServiceAdega.AdegaRepositoryServiceSoap.ModificarAdegaAsync(ServiceAdega.ModificarAdegaRequest request)
        {
            return base.Channel.ModificarAdegaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceAdega.ModificarAdegaResponse> ModificarAdegaAsync(ServiceAdega.Adega adega)
        {
            ServiceAdega.ModificarAdegaRequest inValue = new ServiceAdega.ModificarAdegaRequest();
            inValue.Body = new ServiceAdega.ModificarAdegaRequestBody();
            inValue.Body.adega = adega;
            return ((ServiceAdega.AdegaRepositoryServiceSoap)(this)).ModificarAdegaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceAdega.ApagarAdegaAsyncResponse> ServiceAdega.AdegaRepositoryServiceSoap.ApagarAdegaAsyncAsync(ServiceAdega.ApagarAdegaAsyncRequest request)
        {
            return base.Channel.ApagarAdegaAsyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceAdega.ApagarAdegaAsyncResponse> ApagarAdegaAsyncAsync(int id)
        {
            ServiceAdega.ApagarAdegaAsyncRequest inValue = new ServiceAdega.ApagarAdegaAsyncRequest();
            inValue.Body = new ServiceAdega.ApagarAdegaAsyncRequestBody();
            inValue.Body.id = id;
            return ((ServiceAdega.AdegaRepositoryServiceSoap)(this)).ApagarAdegaAsyncAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AdegaRepositoryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AdegaRepositoryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AdegaRepositoryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/AdegaRepositoryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AdegaRepositoryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/AdegaRepositoryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AdegaRepositoryServiceSoap,
            
            AdegaRepositoryServiceSoap12,
        }
    }
}
