//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSensores
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sensores", Namespace="http://tempuri.org/")]
    public partial class Sensores : object
    {
        
        private int IdField;
        
        private string IdentificadorHardwareField;
        
        private string TipoField;
        
        private bool EstadoField;
        
        private string ImagemUrlField;
        
        private int AdegaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdentificadorHardware
        {
            get
            {
                return this.IdentificadorHardwareField;
            }
            set
            {
                this.IdentificadorHardwareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ImagemUrl
        {
            get
            {
                return this.ImagemUrlField;
            }
            set
            {
                this.ImagemUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int AdegaId
        {
            get
            {
                return this.AdegaIdField;
            }
            set
            {
                this.AdegaIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Leituras", Namespace="http://tempuri.org/")]
    public partial class Leituras : object
    {
        
        private int IdField;
        
        private int SensorIdField;
        
        private float ValorField;
        
        private System.DateTime DataHoraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SensorId
        {
            get
            {
                return this.SensorIdField;
            }
            set
            {
                this.SensorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DataHora
        {
            get
            {
                return this.DataHoraField;
            }
            set
            {
                this.DataHoraField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSensores.SensoresRepositoryServiceSoap")]
    public interface SensoresRepositoryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirSensor", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSensores.InserirSensorResponse> InserirSensorAsync(ServiceSensores.InserirSensorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodosSensores", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSensores.TodosSensoresResponse> TodosSensoresAsync(ServiceSensores.TodosSensoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterSensoresPorAdega", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSensores.ObterSensoresPorAdegaResponse> ObterSensoresPorAdegaAsync(ServiceSensores.ObterSensoresPorAdegaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterLeiturasPorSensor", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSensores.ObterLeiturasPorSensorResponse> ObterLeiturasPorSensorAsync(ServiceSensores.ObterLeiturasPorSensorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirSensorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirSensor", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSensores.InserirSensorRequestBody Body;
        
        public InserirSensorRequest()
        {
        }
        
        public InserirSensorRequest(ServiceSensores.InserirSensorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirSensorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceSensores.Sensores sensor;
        
        public InserirSensorRequestBody()
        {
        }
        
        public InserirSensorRequestBody(ServiceSensores.Sensores sensor)
        {
            this.sensor = sensor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirSensorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirSensorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSensores.InserirSensorResponseBody Body;
        
        public InserirSensorResponse()
        {
        }
        
        public InserirSensorResponse(ServiceSensores.InserirSensorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirSensorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceSensores.Sensores InserirSensorResult;
        
        public InserirSensorResponseBody()
        {
        }
        
        public InserirSensorResponseBody(ServiceSensores.Sensores InserirSensorResult)
        {
            this.InserirSensorResult = InserirSensorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TodosSensoresRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodosSensores", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSensores.TodosSensoresRequestBody Body;
        
        public TodosSensoresRequest()
        {
        }
        
        public TodosSensoresRequest(ServiceSensores.TodosSensoresRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TodosSensoresRequestBody
    {
        
        public TodosSensoresRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TodosSensoresResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodosSensoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSensores.TodosSensoresResponseBody Body;
        
        public TodosSensoresResponse()
        {
        }
        
        public TodosSensoresResponse(ServiceSensores.TodosSensoresResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TodosSensoresResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceSensores.Sensores[] TodosSensoresResult;
        
        public TodosSensoresResponseBody()
        {
        }
        
        public TodosSensoresResponseBody(ServiceSensores.Sensores[] TodosSensoresResult)
        {
            this.TodosSensoresResult = TodosSensoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterSensoresPorAdegaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterSensoresPorAdega", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSensores.ObterSensoresPorAdegaRequestBody Body;
        
        public ObterSensoresPorAdegaRequest()
        {
        }
        
        public ObterSensoresPorAdegaRequest(ServiceSensores.ObterSensoresPorAdegaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterSensoresPorAdegaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int adegaId;
        
        public ObterSensoresPorAdegaRequestBody()
        {
        }
        
        public ObterSensoresPorAdegaRequestBody(int adegaId)
        {
            this.adegaId = adegaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterSensoresPorAdegaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterSensoresPorAdegaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSensores.ObterSensoresPorAdegaResponseBody Body;
        
        public ObterSensoresPorAdegaResponse()
        {
        }
        
        public ObterSensoresPorAdegaResponse(ServiceSensores.ObterSensoresPorAdegaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterSensoresPorAdegaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceSensores.Sensores[] ObterSensoresPorAdegaResult;
        
        public ObterSensoresPorAdegaResponseBody()
        {
        }
        
        public ObterSensoresPorAdegaResponseBody(ServiceSensores.Sensores[] ObterSensoresPorAdegaResult)
        {
            this.ObterSensoresPorAdegaResult = ObterSensoresPorAdegaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterLeiturasPorSensorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterLeiturasPorSensor", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSensores.ObterLeiturasPorSensorRequestBody Body;
        
        public ObterLeiturasPorSensorRequest()
        {
        }
        
        public ObterLeiturasPorSensorRequest(ServiceSensores.ObterLeiturasPorSensorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterLeiturasPorSensorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sensorId;
        
        public ObterLeiturasPorSensorRequestBody()
        {
        }
        
        public ObterLeiturasPorSensorRequestBody(int sensorId)
        {
            this.sensorId = sensorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterLeiturasPorSensorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterLeiturasPorSensorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSensores.ObterLeiturasPorSensorResponseBody Body;
        
        public ObterLeiturasPorSensorResponse()
        {
        }
        
        public ObterLeiturasPorSensorResponse(ServiceSensores.ObterLeiturasPorSensorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterLeiturasPorSensorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceSensores.Leituras[] ObterLeiturasPorSensorResult;
        
        public ObterLeiturasPorSensorResponseBody()
        {
        }
        
        public ObterLeiturasPorSensorResponseBody(ServiceSensores.Leituras[] ObterLeiturasPorSensorResult)
        {
            this.ObterLeiturasPorSensorResult = ObterLeiturasPorSensorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SensoresRepositoryServiceSoapChannel : ServiceSensores.SensoresRepositoryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SensoresRepositoryServiceSoapClient : System.ServiceModel.ClientBase<ServiceSensores.SensoresRepositoryServiceSoap>, ServiceSensores.SensoresRepositoryServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SensoresRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SensoresRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SensoresRepositoryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SensoresRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SensoresRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SensoresRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SensoresRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SensoresRepositoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSensores.InserirSensorResponse> ServiceSensores.SensoresRepositoryServiceSoap.InserirSensorAsync(ServiceSensores.InserirSensorRequest request)
        {
            return base.Channel.InserirSensorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSensores.InserirSensorResponse> InserirSensorAsync(ServiceSensores.Sensores sensor)
        {
            ServiceSensores.InserirSensorRequest inValue = new ServiceSensores.InserirSensorRequest();
            inValue.Body = new ServiceSensores.InserirSensorRequestBody();
            inValue.Body.sensor = sensor;
            return ((ServiceSensores.SensoresRepositoryServiceSoap)(this)).InserirSensorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSensores.TodosSensoresResponse> ServiceSensores.SensoresRepositoryServiceSoap.TodosSensoresAsync(ServiceSensores.TodosSensoresRequest request)
        {
            return base.Channel.TodosSensoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSensores.TodosSensoresResponse> TodosSensoresAsync()
        {
            ServiceSensores.TodosSensoresRequest inValue = new ServiceSensores.TodosSensoresRequest();
            inValue.Body = new ServiceSensores.TodosSensoresRequestBody();
            return ((ServiceSensores.SensoresRepositoryServiceSoap)(this)).TodosSensoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSensores.ObterSensoresPorAdegaResponse> ServiceSensores.SensoresRepositoryServiceSoap.ObterSensoresPorAdegaAsync(ServiceSensores.ObterSensoresPorAdegaRequest request)
        {
            return base.Channel.ObterSensoresPorAdegaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSensores.ObterSensoresPorAdegaResponse> ObterSensoresPorAdegaAsync(int adegaId)
        {
            ServiceSensores.ObterSensoresPorAdegaRequest inValue = new ServiceSensores.ObterSensoresPorAdegaRequest();
            inValue.Body = new ServiceSensores.ObterSensoresPorAdegaRequestBody();
            inValue.Body.adegaId = adegaId;
            return ((ServiceSensores.SensoresRepositoryServiceSoap)(this)).ObterSensoresPorAdegaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSensores.ObterLeiturasPorSensorResponse> ServiceSensores.SensoresRepositoryServiceSoap.ObterLeiturasPorSensorAsync(ServiceSensores.ObterLeiturasPorSensorRequest request)
        {
            return base.Channel.ObterLeiturasPorSensorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSensores.ObterLeiturasPorSensorResponse> ObterLeiturasPorSensorAsync(int sensorId)
        {
            ServiceSensores.ObterLeiturasPorSensorRequest inValue = new ServiceSensores.ObterLeiturasPorSensorRequest();
            inValue.Body = new ServiceSensores.ObterLeiturasPorSensorRequestBody();
            inValue.Body.sensorId = sensorId;
            return ((ServiceSensores.SensoresRepositoryServiceSoap)(this)).ObterLeiturasPorSensorAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SensoresRepositoryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SensoresRepositoryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SensoresRepositoryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/SensoresRepositoryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SensoresRepositoryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/SensoresRepositoryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SensoresRepositoryServiceSoap,
            
            SensoresRepositoryServiceSoap12,
        }
    }
}
