//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAlertas
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alertas", Namespace="http://tempuri.org/")]
    public partial class Alertas : object
    {
        
        private int IdField;
        
        private int SensoresIdField;
        
        private string TipoAlertaField;
        
        private string MensagemField;
        
        private System.DateTime DataHoraField;
        
        private bool ResolvidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SensoresId
        {
            get
            {
                return this.SensoresIdField;
            }
            set
            {
                this.SensoresIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoAlerta
        {
            get
            {
                return this.TipoAlertaField;
            }
            set
            {
                this.TipoAlertaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mensagem
        {
            get
            {
                return this.MensagemField;
            }
            set
            {
                this.MensagemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DataHora
        {
            get
            {
                return this.DataHoraField;
            }
            set
            {
                this.DataHoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Resolvido
        {
            get
            {
                return this.ResolvidoField;
            }
            set
            {
                this.ResolvidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAlertas.AlertasRepositoryServiceSoap")]
    public interface AlertasRepositoryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirAlerta", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceAlertas.InserirAlertaResponse> InserirAlertaAsync(ServiceAlertas.InserirAlertaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterAlertasPorSensor", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceAlertas.ObterAlertasPorSensorResponse> ObterAlertasPorSensorAsync(ServiceAlertas.ObterAlertasPorSensorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirAlertaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirAlerta", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAlertas.InserirAlertaRequestBody Body;
        
        public InserirAlertaRequest()
        {
        }
        
        public InserirAlertaRequest(ServiceAlertas.InserirAlertaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirAlertaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceAlertas.Alertas alerta;
        
        public InserirAlertaRequestBody()
        {
        }
        
        public InserirAlertaRequestBody(ServiceAlertas.Alertas alerta)
        {
            this.alerta = alerta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirAlertaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirAlertaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAlertas.InserirAlertaResponseBody Body;
        
        public InserirAlertaResponse()
        {
        }
        
        public InserirAlertaResponse(ServiceAlertas.InserirAlertaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirAlertaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceAlertas.Alertas InserirAlertaResult;
        
        public InserirAlertaResponseBody()
        {
        }
        
        public InserirAlertaResponseBody(ServiceAlertas.Alertas InserirAlertaResult)
        {
            this.InserirAlertaResult = InserirAlertaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterAlertasPorSensorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterAlertasPorSensor", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAlertas.ObterAlertasPorSensorRequestBody Body;
        
        public ObterAlertasPorSensorRequest()
        {
        }
        
        public ObterAlertasPorSensorRequest(ServiceAlertas.ObterAlertasPorSensorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterAlertasPorSensorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sensorId;
        
        public ObterAlertasPorSensorRequestBody()
        {
        }
        
        public ObterAlertasPorSensorRequestBody(int sensorId)
        {
            this.sensorId = sensorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterAlertasPorSensorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterAlertasPorSensorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceAlertas.ObterAlertasPorSensorResponseBody Body;
        
        public ObterAlertasPorSensorResponse()
        {
        }
        
        public ObterAlertasPorSensorResponse(ServiceAlertas.ObterAlertasPorSensorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterAlertasPorSensorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceAlertas.Alertas[] ObterAlertasPorSensorResult;
        
        public ObterAlertasPorSensorResponseBody()
        {
        }
        
        public ObterAlertasPorSensorResponseBody(ServiceAlertas.Alertas[] ObterAlertasPorSensorResult)
        {
            this.ObterAlertasPorSensorResult = ObterAlertasPorSensorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface AlertasRepositoryServiceSoapChannel : ServiceAlertas.AlertasRepositoryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AlertasRepositoryServiceSoapClient : System.ServiceModel.ClientBase<ServiceAlertas.AlertasRepositoryServiceSoap>, ServiceAlertas.AlertasRepositoryServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AlertasRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AlertasRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), AlertasRepositoryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AlertasRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AlertasRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AlertasRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AlertasRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AlertasRepositoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceAlertas.InserirAlertaResponse> ServiceAlertas.AlertasRepositoryServiceSoap.InserirAlertaAsync(ServiceAlertas.InserirAlertaRequest request)
        {
            return base.Channel.InserirAlertaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceAlertas.InserirAlertaResponse> InserirAlertaAsync(ServiceAlertas.Alertas alerta)
        {
            ServiceAlertas.InserirAlertaRequest inValue = new ServiceAlertas.InserirAlertaRequest();
            inValue.Body = new ServiceAlertas.InserirAlertaRequestBody();
            inValue.Body.alerta = alerta;
            return ((ServiceAlertas.AlertasRepositoryServiceSoap)(this)).InserirAlertaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceAlertas.ObterAlertasPorSensorResponse> ServiceAlertas.AlertasRepositoryServiceSoap.ObterAlertasPorSensorAsync(ServiceAlertas.ObterAlertasPorSensorRequest request)
        {
            return base.Channel.ObterAlertasPorSensorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceAlertas.ObterAlertasPorSensorResponse> ObterAlertasPorSensorAsync(int sensorId)
        {
            ServiceAlertas.ObterAlertasPorSensorRequest inValue = new ServiceAlertas.ObterAlertasPorSensorRequest();
            inValue.Body = new ServiceAlertas.ObterAlertasPorSensorRequestBody();
            inValue.Body.sensorId = sensorId;
            return ((ServiceAlertas.AlertasRepositoryServiceSoap)(this)).ObterAlertasPorSensorAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AlertasRepositoryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AlertasRepositoryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AlertasRepositoryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/AlertasRepositoryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AlertasRepositoryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/AlertasRepositoryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AlertasRepositoryServiceSoap,
            
            AlertasRepositoryServiceSoap12,
        }
    }
}
