//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceVinho
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vinho", Namespace="http://tempuri.org/")]
    public partial class Vinho : object
    {
        
        private int IdField;
        
        private string NomeField;
        
        private string ProdutorField;
        
        private int AnoField;
        
        private string TipoField;
        
        private string DescricaoField;
        
        private string ImagemUrlField;
        
        private float PrecoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Produtor
        {
            get
            {
                return this.ProdutorField;
            }
            set
            {
                this.ProdutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Ano
        {
            get
            {
                return this.AnoField;
            }
            set
            {
                this.AnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ImagemUrl
        {
            get
            {
                return this.ImagemUrlField;
            }
            set
            {
                this.ImagemUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public float Preco
        {
            get
            {
                return this.PrecoField;
            }
            set
            {
                this.PrecoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVinho.VinhoRepositoryServiceSoap")]
    public interface VinhoRepositoryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirVinho", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceVinho.InserirVinhoResponse> InserirVinhoAsync(ServiceVinho.InserirVinhoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarVinho", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceVinho.ModificarVinhoResponse> ModificarVinhoAsync(ServiceVinho.ModificarVinhoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VinhoById", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceVinho.VinhoByIdResponse> VinhoByIdAsync(ServiceVinho.VinhoByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodosVinhos", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceVinho.TodosVinhosResponse> TodosVinhosAsync(ServiceVinho.TodosVinhosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApagarVinho", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ApagarVinhoAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirVinhoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirVinho", Namespace="http://tempuri.org/", Order=0)]
        public ServiceVinho.InserirVinhoRequestBody Body;
        
        public InserirVinhoRequest()
        {
        }
        
        public InserirVinhoRequest(ServiceVinho.InserirVinhoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirVinhoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceVinho.Vinho vinho;
        
        public InserirVinhoRequestBody()
        {
        }
        
        public InserirVinhoRequestBody(ServiceVinho.Vinho vinho)
        {
            this.vinho = vinho;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirVinhoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirVinhoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceVinho.InserirVinhoResponseBody Body;
        
        public InserirVinhoResponse()
        {
        }
        
        public InserirVinhoResponse(ServiceVinho.InserirVinhoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirVinhoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceVinho.Vinho InserirVinhoResult;
        
        public InserirVinhoResponseBody()
        {
        }
        
        public InserirVinhoResponseBody(ServiceVinho.Vinho InserirVinhoResult)
        {
            this.InserirVinhoResult = InserirVinhoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarVinhoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarVinho", Namespace="http://tempuri.org/", Order=0)]
        public ServiceVinho.ModificarVinhoRequestBody Body;
        
        public ModificarVinhoRequest()
        {
        }
        
        public ModificarVinhoRequest(ServiceVinho.ModificarVinhoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarVinhoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceVinho.Vinho vinho;
        
        public ModificarVinhoRequestBody()
        {
        }
        
        public ModificarVinhoRequestBody(ServiceVinho.Vinho vinho)
        {
            this.vinho = vinho;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarVinhoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarVinhoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceVinho.ModificarVinhoResponseBody Body;
        
        public ModificarVinhoResponse()
        {
        }
        
        public ModificarVinhoResponse(ServiceVinho.ModificarVinhoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarVinhoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceVinho.Vinho ModificarVinhoResult;
        
        public ModificarVinhoResponseBody()
        {
        }
        
        public ModificarVinhoResponseBody(ServiceVinho.Vinho ModificarVinhoResult)
        {
            this.ModificarVinhoResult = ModificarVinhoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VinhoByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VinhoById", Namespace="http://tempuri.org/", Order=0)]
        public ServiceVinho.VinhoByIdRequestBody Body;
        
        public VinhoByIdRequest()
        {
        }
        
        public VinhoByIdRequest(ServiceVinho.VinhoByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VinhoByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public VinhoByIdRequestBody()
        {
        }
        
        public VinhoByIdRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VinhoByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VinhoByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceVinho.VinhoByIdResponseBody Body;
        
        public VinhoByIdResponse()
        {
        }
        
        public VinhoByIdResponse(ServiceVinho.VinhoByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VinhoByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceVinho.Vinho VinhoByIdResult;
        
        public VinhoByIdResponseBody()
        {
        }
        
        public VinhoByIdResponseBody(ServiceVinho.Vinho VinhoByIdResult)
        {
            this.VinhoByIdResult = VinhoByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TodosVinhosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodosVinhos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceVinho.TodosVinhosRequestBody Body;
        
        public TodosVinhosRequest()
        {
        }
        
        public TodosVinhosRequest(ServiceVinho.TodosVinhosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TodosVinhosRequestBody
    {
        
        public TodosVinhosRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TodosVinhosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TodosVinhosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceVinho.TodosVinhosResponseBody Body;
        
        public TodosVinhosResponse()
        {
        }
        
        public TodosVinhosResponse(ServiceVinho.TodosVinhosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TodosVinhosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceVinho.Vinho[] TodosVinhosResult;
        
        public TodosVinhosResponseBody()
        {
        }
        
        public TodosVinhosResponseBody(ServiceVinho.Vinho[] TodosVinhosResult)
        {
            this.TodosVinhosResult = TodosVinhosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface VinhoRepositoryServiceSoapChannel : ServiceVinho.VinhoRepositoryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class VinhoRepositoryServiceSoapClient : System.ServiceModel.ClientBase<ServiceVinho.VinhoRepositoryServiceSoap>, ServiceVinho.VinhoRepositoryServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VinhoRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(VinhoRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), VinhoRepositoryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VinhoRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VinhoRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VinhoRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VinhoRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VinhoRepositoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceVinho.InserirVinhoResponse> ServiceVinho.VinhoRepositoryServiceSoap.InserirVinhoAsync(ServiceVinho.InserirVinhoRequest request)
        {
            return base.Channel.InserirVinhoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceVinho.InserirVinhoResponse> InserirVinhoAsync(ServiceVinho.Vinho vinho)
        {
            ServiceVinho.InserirVinhoRequest inValue = new ServiceVinho.InserirVinhoRequest();
            inValue.Body = new ServiceVinho.InserirVinhoRequestBody();
            inValue.Body.vinho = vinho;
            return ((ServiceVinho.VinhoRepositoryServiceSoap)(this)).InserirVinhoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceVinho.ModificarVinhoResponse> ServiceVinho.VinhoRepositoryServiceSoap.ModificarVinhoAsync(ServiceVinho.ModificarVinhoRequest request)
        {
            return base.Channel.ModificarVinhoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceVinho.ModificarVinhoResponse> ModificarVinhoAsync(ServiceVinho.Vinho vinho)
        {
            ServiceVinho.ModificarVinhoRequest inValue = new ServiceVinho.ModificarVinhoRequest();
            inValue.Body = new ServiceVinho.ModificarVinhoRequestBody();
            inValue.Body.vinho = vinho;
            return ((ServiceVinho.VinhoRepositoryServiceSoap)(this)).ModificarVinhoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceVinho.VinhoByIdResponse> ServiceVinho.VinhoRepositoryServiceSoap.VinhoByIdAsync(ServiceVinho.VinhoByIdRequest request)
        {
            return base.Channel.VinhoByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceVinho.VinhoByIdResponse> VinhoByIdAsync(int id)
        {
            ServiceVinho.VinhoByIdRequest inValue = new ServiceVinho.VinhoByIdRequest();
            inValue.Body = new ServiceVinho.VinhoByIdRequestBody();
            inValue.Body.id = id;
            return ((ServiceVinho.VinhoRepositoryServiceSoap)(this)).VinhoByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceVinho.TodosVinhosResponse> ServiceVinho.VinhoRepositoryServiceSoap.TodosVinhosAsync(ServiceVinho.TodosVinhosRequest request)
        {
            return base.Channel.TodosVinhosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceVinho.TodosVinhosResponse> TodosVinhosAsync()
        {
            ServiceVinho.TodosVinhosRequest inValue = new ServiceVinho.TodosVinhosRequest();
            inValue.Body = new ServiceVinho.TodosVinhosRequestBody();
            return ((ServiceVinho.VinhoRepositoryServiceSoap)(this)).TodosVinhosAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> ApagarVinhoAsync(int id)
        {
            return base.Channel.ApagarVinhoAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VinhoRepositoryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.VinhoRepositoryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VinhoRepositoryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/VinhoRepositoryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.VinhoRepositoryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/VinhoRepositoryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            VinhoRepositoryServiceSoap,
            
            VinhoRepositoryServiceSoap12,
        }
    }
}
