//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCompra
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockInput", Namespace="http://tempuri.org/")]
    internal partial class StockInput : object
    {
        
        private int VinhoIdField;
        
        private int AdegaIdField;
        
        private int QuantidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int VinhoId
        {
            get
            {
                return this.VinhoIdField;
            }
            set
            {
                this.VinhoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        internal int AdegaId
        {
            get
            {
                return this.AdegaIdField;
            }
            set
            {
                this.AdegaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        internal int Quantidade
        {
            get
            {
                return this.QuantidadeField;
            }
            set
            {
                this.QuantidadeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    internal class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compra", Namespace="http://tempuri.org/")]
    internal partial class Compra : object
    {
        
        private int IdField;
        
        private string UtilizadorIdField;
        
        private double ValorTotalField;
        
        private System.DateTime DataCompraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string UtilizadorId
        {
            get
            {
                return this.UtilizadorIdField;
            }
            set
            {
                this.UtilizadorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal double ValorTotal
        {
            get
            {
                return this.ValorTotalField;
            }
            set
            {
                this.ValorTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        internal System.DateTime DataCompra
        {
            get
            {
                return this.DataCompraField;
            }
            set
            {
                this.DataCompraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinhaCompra", Namespace="http://tempuri.org/")]
    internal partial class LinhaCompra : object
    {
        
        private int CompraIdField;
        
        private ServiceCompra.ArrayOfInt stockIdsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int CompraId
        {
            get
            {
                return this.CompraIdField;
            }
            set
            {
                this.CompraIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal ServiceCompra.ArrayOfInt stockIds
        {
            get
            {
                return this.stockIdsField;
            }
            set
            {
                this.stockIdsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCompra.CompraRepositoryServiceSoap")]
    internal interface CompraRepositoryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterStockIds", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCompra.ObterStockIdsResponse> ObterStockIdsAsync(ServiceCompra.ObterStockIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CriarCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCompra.CriarCompraResponse> CriarCompraAsync(ServiceCompra.CriarCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdicionarItensCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCompra.AdicionarItensCompraResponse> AdicionarItensCompraAsync(ServiceCompra.AdicionarItensCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinalizarCompra", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCompra.FinalizarCompraResponse> FinalizarCompraAsync(ServiceCompra.FinalizarCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizarValorTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCompra.AtualizarValorTotalResponse> AtualizarValorTotalAsync(ServiceCompra.AtualizarValorTotalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ObterStockIdsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterStockIds", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCompra.ObterStockIdsRequestBody Body;
        
        public ObterStockIdsRequest()
        {
        }
        
        public ObterStockIdsRequest(ServiceCompra.ObterStockIdsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ObterStockIdsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCompra.StockInput stockInput;
        
        public ObterStockIdsRequestBody()
        {
        }
        
        public ObterStockIdsRequestBody(ServiceCompra.StockInput stockInput)
        {
            this.stockInput = stockInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ObterStockIdsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterStockIdsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCompra.ObterStockIdsResponseBody Body;
        
        public ObterStockIdsResponse()
        {
        }
        
        public ObterStockIdsResponse(ServiceCompra.ObterStockIdsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ObterStockIdsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCompra.ArrayOfInt ObterStockIdsResult;
        
        public ObterStockIdsResponseBody()
        {
        }
        
        public ObterStockIdsResponseBody(ServiceCompra.ArrayOfInt ObterStockIdsResult)
        {
            this.ObterStockIdsResult = ObterStockIdsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class CriarCompraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CriarCompra", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCompra.CriarCompraRequestBody Body;
        
        public CriarCompraRequest()
        {
        }
        
        public CriarCompraRequest(ServiceCompra.CriarCompraRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class CriarCompraRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCompra.Compra compra;
        
        public CriarCompraRequestBody()
        {
        }
        
        public CriarCompraRequestBody(ServiceCompra.Compra compra)
        {
            this.compra = compra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class CriarCompraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CriarCompraResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCompra.CriarCompraResponseBody Body;
        
        public CriarCompraResponse()
        {
        }
        
        public CriarCompraResponse(ServiceCompra.CriarCompraResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class CriarCompraResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCompra.Compra CriarCompraResult;
        
        public CriarCompraResponseBody()
        {
        }
        
        public CriarCompraResponseBody(ServiceCompra.Compra CriarCompraResult)
        {
            this.CriarCompraResult = CriarCompraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class AdicionarItensCompraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdicionarItensCompra", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCompra.AdicionarItensCompraRequestBody Body;
        
        public AdicionarItensCompraRequest()
        {
        }
        
        public AdicionarItensCompraRequest(ServiceCompra.AdicionarItensCompraRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class AdicionarItensCompraRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCompra.LinhaCompra linha;
        
        public AdicionarItensCompraRequestBody()
        {
        }
        
        public AdicionarItensCompraRequestBody(ServiceCompra.LinhaCompra linha)
        {
            this.linha = linha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class AdicionarItensCompraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdicionarItensCompraResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCompra.AdicionarItensCompraResponseBody Body;
        
        public AdicionarItensCompraResponse()
        {
        }
        
        public AdicionarItensCompraResponse(ServiceCompra.AdicionarItensCompraResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class AdicionarItensCompraResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AdicionarItensCompraResult;
        
        public AdicionarItensCompraResponseBody()
        {
        }
        
        public AdicionarItensCompraResponseBody(bool AdicionarItensCompraResult)
        {
            this.AdicionarItensCompraResult = AdicionarItensCompraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class FinalizarCompraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizarCompra", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCompra.FinalizarCompraRequestBody Body;
        
        public FinalizarCompraRequest()
        {
        }
        
        public FinalizarCompraRequest(ServiceCompra.FinalizarCompraRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class FinalizarCompraRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCompra.LinhaCompra linha;
        
        public FinalizarCompraRequestBody()
        {
        }
        
        public FinalizarCompraRequestBody(ServiceCompra.LinhaCompra linha)
        {
            this.linha = linha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class FinalizarCompraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FinalizarCompraResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCompra.FinalizarCompraResponseBody Body;
        
        public FinalizarCompraResponse()
        {
        }
        
        public FinalizarCompraResponse(ServiceCompra.FinalizarCompraResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class FinalizarCompraResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FinalizarCompraResult;
        
        public FinalizarCompraResponseBody()
        {
        }
        
        public FinalizarCompraResponseBody(bool FinalizarCompraResult)
        {
            this.FinalizarCompraResult = FinalizarCompraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class AtualizarValorTotalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarValorTotal", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCompra.AtualizarValorTotalRequestBody Body;
        
        public AtualizarValorTotalRequest()
        {
        }
        
        public AtualizarValorTotalRequest(ServiceCompra.AtualizarValorTotalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class AtualizarValorTotalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCompra.Compra compra;
        
        public AtualizarValorTotalRequestBody()
        {
        }
        
        public AtualizarValorTotalRequestBody(ServiceCompra.Compra compra)
        {
            this.compra = compra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class AtualizarValorTotalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarValorTotalResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCompra.AtualizarValorTotalResponseBody Body;
        
        public AtualizarValorTotalResponse()
        {
        }
        
        public AtualizarValorTotalResponse(ServiceCompra.AtualizarValorTotalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class AtualizarValorTotalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AtualizarValorTotalResult;
        
        public AtualizarValorTotalResponseBody()
        {
        }
        
        public AtualizarValorTotalResponseBody(bool AtualizarValorTotalResult)
        {
            this.AtualizarValorTotalResult = AtualizarValorTotalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal interface CompraRepositoryServiceSoapChannel : ServiceCompra.CompraRepositoryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    internal partial class CompraRepositoryServiceSoapClient : System.ServiceModel.ClientBase<ServiceCompra.CompraRepositoryServiceSoap>, ServiceCompra.CompraRepositoryServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CompraRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CompraRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), CompraRepositoryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompraRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CompraRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompraRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CompraRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompraRepositoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceCompra.ObterStockIdsResponse> ServiceCompra.CompraRepositoryServiceSoap.ObterStockIdsAsync(ServiceCompra.ObterStockIdsRequest request)
        {
            return base.Channel.ObterStockIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCompra.ObterStockIdsResponse> ObterStockIdsAsync(ServiceCompra.StockInput stockInput)
        {
            ServiceCompra.ObterStockIdsRequest inValue = new ServiceCompra.ObterStockIdsRequest();
            inValue.Body = new ServiceCompra.ObterStockIdsRequestBody();
            inValue.Body.stockInput = stockInput;
            return ((ServiceCompra.CompraRepositoryServiceSoap)(this)).ObterStockIdsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceCompra.CriarCompraResponse> ServiceCompra.CompraRepositoryServiceSoap.CriarCompraAsync(ServiceCompra.CriarCompraRequest request)
        {
            return base.Channel.CriarCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCompra.CriarCompraResponse> CriarCompraAsync(ServiceCompra.Compra compra)
        {
            ServiceCompra.CriarCompraRequest inValue = new ServiceCompra.CriarCompraRequest();
            inValue.Body = new ServiceCompra.CriarCompraRequestBody();
            inValue.Body.compra = compra;
            return ((ServiceCompra.CompraRepositoryServiceSoap)(this)).CriarCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceCompra.AdicionarItensCompraResponse> ServiceCompra.CompraRepositoryServiceSoap.AdicionarItensCompraAsync(ServiceCompra.AdicionarItensCompraRequest request)
        {
            return base.Channel.AdicionarItensCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCompra.AdicionarItensCompraResponse> AdicionarItensCompraAsync(ServiceCompra.LinhaCompra linha)
        {
            ServiceCompra.AdicionarItensCompraRequest inValue = new ServiceCompra.AdicionarItensCompraRequest();
            inValue.Body = new ServiceCompra.AdicionarItensCompraRequestBody();
            inValue.Body.linha = linha;
            return ((ServiceCompra.CompraRepositoryServiceSoap)(this)).AdicionarItensCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceCompra.FinalizarCompraResponse> ServiceCompra.CompraRepositoryServiceSoap.FinalizarCompraAsync(ServiceCompra.FinalizarCompraRequest request)
        {
            return base.Channel.FinalizarCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCompra.FinalizarCompraResponse> FinalizarCompraAsync(ServiceCompra.LinhaCompra linha)
        {
            ServiceCompra.FinalizarCompraRequest inValue = new ServiceCompra.FinalizarCompraRequest();
            inValue.Body = new ServiceCompra.FinalizarCompraRequestBody();
            inValue.Body.linha = linha;
            return ((ServiceCompra.CompraRepositoryServiceSoap)(this)).FinalizarCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceCompra.AtualizarValorTotalResponse> ServiceCompra.CompraRepositoryServiceSoap.AtualizarValorTotalAsync(ServiceCompra.AtualizarValorTotalRequest request)
        {
            return base.Channel.AtualizarValorTotalAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCompra.AtualizarValorTotalResponse> AtualizarValorTotalAsync(ServiceCompra.Compra compra)
        {
            ServiceCompra.AtualizarValorTotalRequest inValue = new ServiceCompra.AtualizarValorTotalRequest();
            inValue.Body = new ServiceCompra.AtualizarValorTotalRequestBody();
            inValue.Body.compra = compra;
            return ((ServiceCompra.CompraRepositoryServiceSoap)(this)).AtualizarValorTotalAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CompraRepositoryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CompraRepositoryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CompraRepositoryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/CompraRepositoryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CompraRepositoryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/CompraRepositoryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CompraRepositoryServiceSoap,
            
            CompraRepositoryServiceSoap12,
        }
    }
}
