//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCarrinho
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carrinho", Namespace="http://tempuri.org/")]
    public partial class Carrinho : object
    {
        
        private int IdField;
        
        private int VinhosIdField;
        
        private string UtilizadoresIdField;
        
        private int QuantidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VinhosId
        {
            get
            {
                return this.VinhosIdField;
            }
            set
            {
                this.VinhosIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UtilizadoresId
        {
            get
            {
                return this.UtilizadoresIdField;
            }
            set
            {
                this.UtilizadoresIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Quantidade
        {
            get
            {
                return this.QuantidadeField;
            }
            set
            {
                this.QuantidadeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCarrinho.CarrinhoRepositoryServiceSoap")]
    public interface CarrinhoRepositoryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterCarrinhoPorUtilizador", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCarrinho.ObterCarrinhoPorUtilizadorResponse> ObterCarrinhoPorUtilizadorAsync(ServiceCarrinho.ObterCarrinhoPorUtilizadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirItem", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCarrinho.InserirItemResponse> InserirItemAsync(ServiceCarrinho.InserirItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AtualizarItem", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceCarrinho.AtualizarItemResponse> AtualizarItemAsync(ServiceCarrinho.AtualizarItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarItem", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarItemAsync(int itemId, int utilizadoresId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterCarrinhoPorUtilizadorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterCarrinhoPorUtilizador", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCarrinho.ObterCarrinhoPorUtilizadorRequestBody Body;
        
        public ObterCarrinhoPorUtilizadorRequest()
        {
        }
        
        public ObterCarrinhoPorUtilizadorRequest(ServiceCarrinho.ObterCarrinhoPorUtilizadorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterCarrinhoPorUtilizadorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string utilizadoresId;
        
        public ObterCarrinhoPorUtilizadorRequestBody()
        {
        }
        
        public ObterCarrinhoPorUtilizadorRequestBody(string utilizadoresId)
        {
            this.utilizadoresId = utilizadoresId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterCarrinhoPorUtilizadorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterCarrinhoPorUtilizadorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCarrinho.ObterCarrinhoPorUtilizadorResponseBody Body;
        
        public ObterCarrinhoPorUtilizadorResponse()
        {
        }
        
        public ObterCarrinhoPorUtilizadorResponse(ServiceCarrinho.ObterCarrinhoPorUtilizadorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterCarrinhoPorUtilizadorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCarrinho.Carrinho[] ObterCarrinhoPorUtilizadorResult;
        
        public ObterCarrinhoPorUtilizadorResponseBody()
        {
        }
        
        public ObterCarrinhoPorUtilizadorResponseBody(ServiceCarrinho.Carrinho[] ObterCarrinhoPorUtilizadorResult)
        {
            this.ObterCarrinhoPorUtilizadorResult = ObterCarrinhoPorUtilizadorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirItemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirItem", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCarrinho.InserirItemRequestBody Body;
        
        public InserirItemRequest()
        {
        }
        
        public InserirItemRequest(ServiceCarrinho.InserirItemRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirItemRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCarrinho.Carrinho itemCarrinho;
        
        public InserirItemRequestBody()
        {
        }
        
        public InserirItemRequestBody(ServiceCarrinho.Carrinho itemCarrinho)
        {
            this.itemCarrinho = itemCarrinho;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirItemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCarrinho.InserirItemResponseBody Body;
        
        public InserirItemResponse()
        {
        }
        
        public InserirItemResponse(ServiceCarrinho.InserirItemResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirItemResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCarrinho.Carrinho[] InserirItemResult;
        
        public InserirItemResponseBody()
        {
        }
        
        public InserirItemResponseBody(ServiceCarrinho.Carrinho[] InserirItemResult)
        {
            this.InserirItemResult = InserirItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarItemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarItem", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCarrinho.AtualizarItemRequestBody Body;
        
        public AtualizarItemRequest()
        {
        }
        
        public AtualizarItemRequest(ServiceCarrinho.AtualizarItemRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarItemRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCarrinho.Carrinho itemCarrinho;
        
        public AtualizarItemRequestBody()
        {
        }
        
        public AtualizarItemRequestBody(ServiceCarrinho.Carrinho itemCarrinho)
        {
            this.itemCarrinho = itemCarrinho;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AtualizarItemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AtualizarItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceCarrinho.AtualizarItemResponseBody Body;
        
        public AtualizarItemResponse()
        {
        }
        
        public AtualizarItemResponse(ServiceCarrinho.AtualizarItemResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AtualizarItemResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceCarrinho.Carrinho[] AtualizarItemResult;
        
        public AtualizarItemResponseBody()
        {
        }
        
        public AtualizarItemResponseBody(ServiceCarrinho.Carrinho[] AtualizarItemResult)
        {
            this.AtualizarItemResult = AtualizarItemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface CarrinhoRepositoryServiceSoapChannel : ServiceCarrinho.CarrinhoRepositoryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CarrinhoRepositoryServiceSoapClient : System.ServiceModel.ClientBase<ServiceCarrinho.CarrinhoRepositoryServiceSoap>, ServiceCarrinho.CarrinhoRepositoryServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CarrinhoRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CarrinhoRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), CarrinhoRepositoryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarrinhoRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CarrinhoRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarrinhoRepositoryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CarrinhoRepositoryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarrinhoRepositoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceCarrinho.ObterCarrinhoPorUtilizadorResponse> ServiceCarrinho.CarrinhoRepositoryServiceSoap.ObterCarrinhoPorUtilizadorAsync(ServiceCarrinho.ObterCarrinhoPorUtilizadorRequest request)
        {
            return base.Channel.ObterCarrinhoPorUtilizadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCarrinho.ObterCarrinhoPorUtilizadorResponse> ObterCarrinhoPorUtilizadorAsync(string utilizadoresId)
        {
            ServiceCarrinho.ObterCarrinhoPorUtilizadorRequest inValue = new ServiceCarrinho.ObterCarrinhoPorUtilizadorRequest();
            inValue.Body = new ServiceCarrinho.ObterCarrinhoPorUtilizadorRequestBody();
            inValue.Body.utilizadoresId = utilizadoresId;
            return ((ServiceCarrinho.CarrinhoRepositoryServiceSoap)(this)).ObterCarrinhoPorUtilizadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceCarrinho.InserirItemResponse> ServiceCarrinho.CarrinhoRepositoryServiceSoap.InserirItemAsync(ServiceCarrinho.InserirItemRequest request)
        {
            return base.Channel.InserirItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCarrinho.InserirItemResponse> InserirItemAsync(ServiceCarrinho.Carrinho itemCarrinho)
        {
            ServiceCarrinho.InserirItemRequest inValue = new ServiceCarrinho.InserirItemRequest();
            inValue.Body = new ServiceCarrinho.InserirItemRequestBody();
            inValue.Body.itemCarrinho = itemCarrinho;
            return ((ServiceCarrinho.CarrinhoRepositoryServiceSoap)(this)).InserirItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceCarrinho.AtualizarItemResponse> ServiceCarrinho.CarrinhoRepositoryServiceSoap.AtualizarItemAsync(ServiceCarrinho.AtualizarItemRequest request)
        {
            return base.Channel.AtualizarItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceCarrinho.AtualizarItemResponse> AtualizarItemAsync(ServiceCarrinho.Carrinho itemCarrinho)
        {
            ServiceCarrinho.AtualizarItemRequest inValue = new ServiceCarrinho.AtualizarItemRequest();
            inValue.Body = new ServiceCarrinho.AtualizarItemRequestBody();
            inValue.Body.itemCarrinho = itemCarrinho;
            return ((ServiceCarrinho.CarrinhoRepositoryServiceSoap)(this)).AtualizarItemAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarItemAsync(int itemId, int utilizadoresId)
        {
            return base.Channel.EliminarItemAsync(itemId, utilizadoresId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CarrinhoRepositoryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CarrinhoRepositoryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CarrinhoRepositoryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/CarrinhoRepositoryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CarrinhoRepositoryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44320/Services/CarrinhoRepositoryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CarrinhoRepositoryServiceSoap,
            
            CarrinhoRepositoryServiceSoap12,
        }
    }
}
